name: inspect
on:
  push:
jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Show kernal and files
        run: |
          uname -a
          ls -la
      - name: Number of files in the repository
        run: git ls-files | wc -l
