name: notify
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      NOTIFY_TOKEN:
        required: true
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: echoing
        run: echo "Environment ${{ inputs.environment }}"
