name: pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.ver.outputs.version}}
    steps:
      - name: compute version
        id: ver
        run: echo "version=1.4.2" >> "$GITHUB_OUTPUT"
