name: secret-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checks secrets
        env:
          APP_TOKEN: ${{secrets.APP_TOKEN}}
        run: |
          if [ -n "$APP_TOKEN" ]; then
            echo "token is available"
          fi
        echo "$APP_TOKEN"
